# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 482e2bef63f2d648e09acd40ead5f4fb80bbc6b41d931231d4182bbf1c138d0e4572a2b3e3ccae1105a26ad0ea24add6fd29fded5538cb177769ec089f0f26c1

test:
  secret_key_base: 7a9744bce5f6792b969bd5ed448c84e1fd7edf6a00e7243d40d2628cec53a89661bb2f4ba6908fc6409be201d9b174fb5ab76ace3f30958ce5976a76db1bf286

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
